apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod
  namespace: expense
  labels:
    app: demo
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
